import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// ============================================================
// 200 UNIQUE QUESTIONS — 40 per category, ZERO repetition
// Categories: ENGLISH | NUMERICAL_APTITUDE | GENERAL_AWARENESS
//             BASIC_ENGINEERING | MATHEMATICS
// Quiz format: 25 Q total → 5 per category
//
// Project by: MITRASEN YADAV, MTECH CSE, NIT Hamirpur
// ============================================================

const allQuestions = [

  // ==================== ENGLISH (40 unique) ====================
  { category: "ENGLISH", difficulty: "easy",
    text: "Choose the correct spelling:",
    optionA: "Accomodation", optionB: "Accommodation", optionC: "Acommodation", optionD: "Acomodation", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "The synonym of 'Benevolent' is:",
    optionA: "Cruel", optionB: "Indifferent", optionC: "Kind", optionD: "Greedy", correct: "C" },
  { category: "ENGLISH", difficulty: "easy",
    text: "The antonym of 'Transparent' is:",
    optionA: "Clear", optionB: "Opaque", optionC: "Shiny", optionD: "Bright", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Fill in the blank: She ___ to school every day.",
    optionA: "go", optionB: "goes", optionC: "going", optionD: "gone", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "One word for 'A person who repairs shoes':",
    optionA: "Carpenter", optionB: "Cobbler", optionC: "Mason", optionD: "Tailor", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Passive voice of 'She wrote a letter':",
    optionA: "A letter is written by her", optionB: "A letter was written by her", optionC: "A letter has been written by her", optionD: "A letter had been written by her", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "The plural of 'Phenomenon' is:",
    optionA: "Phenomenons", optionB: "Phenomenas", optionC: "Phenomena", optionD: "Phenomen", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Choose the correctly punctuated sentence:",
    optionA: "Its a beautiful day", optionB: "It's a beautiful day", optionC: "Its' a beautiful day", optionD: "Its a beautiful, day", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Idiom 'Break the ice' means:",
    optionA: "Destroy something frozen", optionB: "Start a conversation in an awkward situation", optionC: "Stop an argument", optionD: "Do something illegal", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "The synonym of 'Eloquent' is:",
    optionA: "Silent", optionB: "Articulate", optionC: "Confused", optionD: "Rude", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Choose the correct sentence:",
    optionA: "Neither of them are correct", optionB: "Neither of them is correct", optionC: "Neither of them were correct", optionD: "Neither of them have been correct", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "The figure of speech in 'Life is a journey' is:",
    optionA: "Simile", optionB: "Personification", optionC: "Metaphor", optionD: "Hyperbole", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Indirect speech: He said 'I am happy.' becomes:",
    optionA: "He said he is happy", optionB: "He said he was happy", optionC: "He said he had been happy", optionD: "He said he were happy", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Collective noun for a group of bees:",
    optionA: "Herd", optionB: "Swarm", optionC: "Pack", optionD: "Flock", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "The antonym of 'Austere' is:",
    optionA: "Strict", optionB: "Harsh", optionC: "Lavish", optionD: "Stern", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Fill in: He ___ dinner when I called him.",
    optionA: "has", optionB: "had", optionC: "was having", optionD: "is having", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Choose correct: ___ honest man is respected by all.",
    optionA: "A", optionB: "An", optionC: "The", optionD: "No article needed", correct: "B" },
  { category: "ENGLISH", difficulty: "hard",
    text: "One word for 'Fear of heights':",
    optionA: "Claustrophobia", optionB: "Agoraphobia", optionC: "Acrophobia", optionD: "Hydrophobia", correct: "C" },
  { category: "ENGLISH", difficulty: "hard",
    text: "Identify the error: 'He is one of those student who works hard.'",
    optionA: "He is", optionB: "those", optionC: "student", optionD: "works hard", correct: "C" },
  { category: "ENGLISH", difficulty: "hard",
    text: "Synonym of 'Perspicacious':",
    optionA: "Dull", optionB: "Shrewd", optionC: "Lazy", optionD: "Timid", correct: "B" },
  { category: "ENGLISH", difficulty: "hard",
    text: "The sentence type of 'What a beautiful morning!' is:",
    optionA: "Declarative", optionB: "Interrogative", optionC: "Exclamatory", optionD: "Imperative", correct: "C" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Which word is a noun in: 'The quick brown fox jumps'?",
    optionA: "quick", optionB: "brown", optionC: "fox", optionD: "jumps", correct: "C" },
  { category: "ENGLISH", difficulty: "easy",
    text: "The word 'Quickly' is a/an:",
    optionA: "Noun", optionB: "Adjective", optionC: "Adverb", optionD: "Verb", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Fill in the blank: The jury ___ divided on the verdict.",
    optionA: "were", optionB: "was", optionC: "are", optionD: "have", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "'Cost an arm and ___' — complete the idiom:",
    optionA: "a foot", optionB: "a leg", optionC: "a hand", optionD: "a neck", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Correct spelling of the word meaning 'happening once a year':",
    optionA: "Anual", optionB: "Annuall", optionC: "Annual", optionD: "Annuel", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Antonym of 'Optimistic':",
    optionA: "Hopeful", optionB: "Cheerful", optionC: "Pessimistic", optionD: "Positive", correct: "C" },
  { category: "ENGLISH", difficulty: "hard",
    text: "Proverb: 'Actions speak louder than ___':",
    optionA: "silence", optionB: "thoughts", optionC: "words", optionD: "deeds", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "The preposition in 'She sat on the chair' is:",
    optionA: "She", optionB: "sat", optionC: "on", optionD: "chair", correct: "C" },
  { category: "ENGLISH", difficulty: "hard",
    text: "Synonym of 'Gregarious':",
    optionA: "Lonely", optionB: "Sociable", optionC: "Hostile", optionD: "Timid", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Choose correct tense: By 2030, scientists ___ a cure for cancer.",
    optionA: "will find", optionB: "will have found", optionC: "found", optionD: "have found", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Opposite of 'Verbose' is:",
    optionA: "Wordy", optionB: "Talkative", optionC: "Concise", optionD: "Loud", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Which sentence uses the subjunctive mood correctly?",
    optionA: "If I was rich, I would travel", optionB: "If I were rich, I would travel", optionC: "If I am rich, I would travel", optionD: "If I be rich, I would travel", correct: "B" },
  { category: "ENGLISH", difficulty: "hard",
    text: "The literary device in 'The stars danced in the night sky' is:",
    optionA: "Simile", optionB: "Metaphor", optionC: "Personification", optionD: "Alliteration", correct: "C" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Antonym of 'Ancient' is:",
    optionA: "Old", optionB: "Aged", optionC: "Modern", optionD: "Historic", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "Choose the correct form: The news ___ surprising.",
    optionA: "are", optionB: "were", optionC: "is", optionD: "have been", correct: "C" },
  { category: "ENGLISH", difficulty: "hard",
    text: "Identify the correct sentence:",
    optionA: "Whom shall I say is calling?", optionB: "Who shall I say is calling?", optionC: "Who shall I say are calling?", optionD: "Whom shall I say are calling?", correct: "B" },
  { category: "ENGLISH", difficulty: "medium",
    text: "'Burning the midnight oil' means:",
    optionA: "Lighting a lamp", optionB: "Working very late at night", optionC: "Wasting oil", optionD: "Starting a fire", correct: "B" },
  { category: "ENGLISH", difficulty: "easy",
    text: "Synonym of 'Abundant':",
    optionA: "Scarce", optionB: "Limited", optionC: "Plentiful", optionD: "Rare", correct: "C" },
  { category: "ENGLISH", difficulty: "medium",
    text: "In 'She gave him a book', 'him' is a/an:",
    optionA: "Direct object", optionB: "Indirect object", optionC: "Subject", optionD: "Predicate", correct: "B" },

  // ==================== NUMERICAL APTITUDE (40 unique) ====================
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "What is 15% of 240?",
    optionA: "30", optionB: "36", optionC: "40", optionD: "24", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "A shopkeeper buys at Rs.500 and sells at 20% profit. SP = ?",
    optionA: "Rs.550", optionB: "Rs.600", optionC: "Rs.620", optionD: "Rs.580", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "Simple interest on Rs.1000 at 5% p.a. for 3 years = ?",
    optionA: "Rs.100", optionB: "Rs.150", optionC: "Rs.200", optionD: "Rs.250", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "A car covers 120 km at 60 km/h. Time taken = ?",
    optionA: "1 hr", optionB: "2 hrs", optionC: "1.5 hrs", optionD: "2.5 hrs", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "Average of 10, 20, 30, 40, 50 = ?",
    optionA: "25", optionB: "30", optionC: "35", optionD: "40", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "Two numbers in ratio 3:5 have sum 80. Smaller number = ?",
    optionA: "24", optionB: "30", optionC: "32", optionD: "35", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "20 is what percent of 80?",
    optionA: "15%", optionB: "20%", optionC: "25%", optionD: "30%", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "HCF of 24 and 36 = ?",
    optionA: "6", optionB: "12", optionC: "18", optionD: "24", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "LCM of 12 and 18 = ?",
    optionA: "24", optionB: "36", optionC: "48", optionD: "72", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "Pipe A fills a tank in 6 hrs, pipe B in 3 hrs. Together they fill in:",
    optionA: "1.5 hrs", optionB: "2 hrs", optionC: "2.5 hrs", optionD: "4 hrs", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Compound interest on Rs.1000 at 10% p.a. for 2 years = ?",
    optionA: "Rs.200", optionB: "Rs.210", optionC: "Rs.220", optionD: "Rs.250", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A train 150m long crosses a pole in 5 seconds. Speed of train in km/h = ?",
    optionA: "90 km/h", optionB: "108 km/h", optionC: "120 km/h", optionD: "72 km/h", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A and B can do a work in 12 and 6 days respectively. Together they finish in:",
    optionA: "3 days", optionB: "4 days", optionC: "5 days", optionD: "6 days", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A discount of 10% on MRP Rs.500 gives SP = ?",
    optionA: "Rs.400", optionB: "Rs.450", optionC: "Rs.440", optionD: "Rs.460", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "If 40% of x = 120, then x = ?",
    optionA: "280", optionB: "300", optionC: "320", optionD: "340", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Speed of boat in still water = 10 km/h, current = 2 km/h. Downstream speed = ?",
    optionA: "8 km/h", optionB: "10 km/h", optionC: "12 km/h", optionD: "14 km/h", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Profit % = 40, CP = Rs.350. SP = ?",
    optionA: "Rs.480", optionB: "Rs.490", optionC: "Rs.450", optionD: "Rs.500", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "P:Q = 2:3 and Q:R = 4:5. P:R = ?",
    optionA: "8:15", optionB: "2:5", optionC: "4:5", optionD: "6:10", correct: "A" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Mode of: 4, 5, 6, 5, 4, 5, 7 = ?",
    optionA: "4", optionB: "5", optionC: "6", optionD: "7", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A man walks 4 km North, then 3 km East. Distance from starting point = ?",
    optionA: "5 km", optionB: "6 km", optionC: "7 km", optionD: "4 km", correct: "A" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "A sum triples itself in 4 years at Simple Interest. Rate of interest p.a. = ?",
    optionA: "25%", optionB: "40%", optionC: "50%", optionD: "60%", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "In how many ways can 4 people sit in a row of 4 chairs?",
    optionA: "8", optionB: "16", optionC: "24", optionD: "32", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "A dealer marks up 30% and gives 10% discount. Net profit% = ?",
    optionA: "15%", optionB: "17%", optionC: "20%", optionD: "22%", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "Two pipes fill a tank in 20 and 30 min. A drain empties in 60 min. All three open together fill in:",
    optionA: "10 min", optionB: "12 min", optionC: "15 min", optionD: "18 min", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "What is the square of 13?",
    optionA: "144", optionB: "156", optionC: "169", optionD: "196", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "Cube root of 512 = ?",
    optionA: "6", optionB: "7", optionC: "8", optionD: "9", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "If a clock shows 3:00, the angle between its hands is:",
    optionA: "60°", optionB: "75°", optionC: "90°", optionD: "120°", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A man spends 75% of his income. If his income is Rs.12000, he saves:",
    optionA: "Rs.2000", optionB: "Rs.3000", optionC: "Rs.3500", optionD: "Rs.4000", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "In a bag: 3 red, 4 blue, 5 green balls. Probability of picking a red ball = ?",
    optionA: "1/4", optionB: "1/3", optionC: "1/5", optionD: "1/6", correct: "A" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Sum of first 10 natural numbers = ?",
    optionA: "45", optionB: "50", optionC: "55", optionD: "60", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A number increased by 20% becomes 84. Original number = ?",
    optionA: "60", optionB: "65", optionC: "70", optionD: "75", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "The ratio of boys to girls in a class is 3:2. If there are 30 students total, how many girls?",
    optionA: "10", optionB: "12", optionC: "15", optionD: "18", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "Average age of 5 people is 30. One person aged 20 is replaced by someone aged 40. New average = ?",
    optionA: "32", optionB: "34", optionC: "36", optionD: "38", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "If 3x + 7 = 22, then x = ?",
    optionA: "3", optionB: "4", optionC: "5", optionD: "6", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A train running at 72 km/h crosses a 200m bridge in 10 seconds. Length of train = ?",
    optionA: "100 m", optionB: "150 m", optionC: "200 m", optionD: "250 m", correct: "A" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "A and B together earn Rs.1200/day, B and C earn Rs.1000/day, A and C earn Rs.800/day. A's daily earnings = ?",
    optionA: "Rs.400", optionB: "Rs.450", optionC: "Rs.500", optionD: "Rs.550", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "easy",
    text: "What is the perimeter of a rectangle with L=12 cm, B=8 cm?",
    optionA: "36 cm", optionB: "40 cm", optionC: "44 cm", optionD: "96 cm", correct: "B" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "A bucket holds 12 litres. If it is 3/4 full, how many litres are in it?",
    optionA: "6", optionB: "8", optionC: "9", optionD: "10", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "hard",
    text: "What is 2 to the power 3 multiplied by 3 squared plus 5?",
    optionA: "65", optionB: "75", optionC: "77", optionD: "81", correct: "C" },
  { category: "NUMERICAL_APTITUDE", difficulty: "medium",
    text: "If the selling price of 10 articles equals the cost price of 12 articles, profit% = ?",
    optionA: "15%", optionB: "20%", optionC: "22%", optionD: "25%", correct: "B" },

  // ==================== GENERAL AWARENESS (40 unique) ====================
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "Who is known as the Father of the Indian Constitution?",
    optionA: "Mahatma Gandhi", optionB: "Dr. B.R. Ambedkar", optionC: "Jawaharlal Nehru", optionD: "Sardar Patel", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The capital of India is:",
    optionA: "Mumbai", optionB: "Kolkata", optionC: "Chennai", optionD: "New Delhi", correct: "D" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The largest planet in our Solar System is:",
    optionA: "Saturn", optionB: "Neptune", optionC: "Jupiter", optionD: "Uranus", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The currency of Japan is:",
    optionA: "Yuan", optionB: "Won", optionC: "Yen", optionD: "Ringgit", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "World Computer Literacy Day is observed on:",
    optionA: "November 2", optionB: "December 2", optionC: "October 2", optionD: "January 2", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The headquarters of ISRO is located in:",
    optionA: "Mumbai", optionB: "Hyderabad", optionC: "Bengaluru", optionD: "Pune", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The chemical formula of water is:",
    optionA: "H2O2", optionB: "HO2", optionC: "H2O", optionD: "OH2", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The national animal of India is:",
    optionA: "Lion", optionB: "Elephant", optionC: "Tiger", optionD: "Leopard", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "India's first satellite launched into space was:",
    optionA: "Bhaskara", optionB: "Aryabhatta", optionC: "Rohini", optionD: "INSAT-1A", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The Chandrayaan-3 mission successfully landed on the Moon in:",
    optionA: "2021", optionB: "2022", optionC: "2023", optionD: "2024", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "NIT Hamirpur is located in which state of India?",
    optionA: "Uttarakhand", optionB: "Punjab", optionC: "Himachal Pradesh", optionD: "Haryana", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "G20 Summit 2023 was hosted by:",
    optionA: "Brazil", optionB: "Japan", optionC: "India", optionD: "USA", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The first woman to go into space was:",
    optionA: "Sally Ride", optionB: "Valentina Tereshkova", optionC: "Kalpana Chawla", optionD: "Sunita Williams", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Who invented the telephone?",
    optionA: "Thomas Edison", optionB: "Nikola Tesla", optionC: "Alexander Graham Bell", optionD: "Guglielmo Marconi", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The full form of 'CPU' in computing is:",
    optionA: "Central Processing Unit", optionB: "Computer Programming Unit", optionC: "Central Program Utility", optionD: "Core Processing Unit", correct: "A" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The programming language Python was created by:",
    optionA: "Dennis Ritchie", optionB: "James Gosling", optionC: "Guido van Rossum", optionD: "Bjarne Stroustrup", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which company developed the Android operating system?",
    optionA: "Apple", optionB: "Microsoft", optionC: "Samsung", optionD: "Google", correct: "D" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "The term 'Artificial Intelligence' was coined by:",
    optionA: "Alan Turing", optionB: "John McCarthy", optionC: "Claude Shannon", optionD: "Marvin Minsky", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "India's first supercomputer was named:",
    optionA: "PARAM 8000", optionB: "ANURAG", optionC: "Saga 220", optionD: "Samkhyan", correct: "A" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "The International Day of Mathematics (Pi Day) is observed on:",
    optionA: "March 14", optionB: "April 22", optionC: "February 28", optionD: "May 10", correct: "A" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The speed of light is approximately:",
    optionA: "3 x 10^6 m/s", optionB: "3 x 10^8 m/s", optionC: "3 x 10^10 m/s", optionD: "3 x 10^4 m/s", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which scientist gave the laws of motion?",
    optionA: "Albert Einstein", optionB: "Isaac Newton", optionC: "Galileo Galilei", optionD: "Nikola Tesla", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The Turing Award is considered the Nobel Prize of:",
    optionA: "Physics", optionB: "Mathematics", optionC: "Computing", optionD: "Engineering", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "The National Technology Day of India is observed on:",
    optionA: "May 11", optionB: "July 11", optionC: "August 15", optionD: "October 11", correct: "A" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "HTTP stands for:",
    optionA: "HyperText Transfer Protocol", optionB: "High Text Transfer Protocol", optionC: "HyperText Transmission Protocol", optionD: "Hybrid Transfer Text Protocol", correct: "A" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "Which planet is closest to the Sun?",
    optionA: "Venus", optionB: "Mars", optionC: "Mercury", optionD: "Earth", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The binary number system uses how many digits?",
    optionA: "8", optionB: "10", optionC: "16", optionD: "2", correct: "D" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which Indian engineer co-founded Sun Microsystems?",
    optionA: "Azim Premji", optionB: "Vinod Khosla", optionC: "Narayana Murthy", optionD: "Shiv Nadar", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "The first electronic general-purpose computer was:",
    optionA: "UNIVAC", optionB: "ENIAC", optionC: "EDVAC", optionD: "Mark 1", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Silicon Valley is located in which US state?",
    optionA: "New York", optionB: "Texas", optionC: "California", optionD: "Washington", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "What does RAM stand for in computing?",
    optionA: "Read Access Memory", optionB: "Random Access Memory", optionC: "Rapid Access Module", optionD: "Read And Modify", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "IEEE stands for:",
    optionA: "Institute of Electrical and Engineering Electronics", optionB: "Institute of Electrical and Electronics Engineers", optionC: "International Electronics and Engineering Enterprise", optionD: "Indian Engineering and Electronics Examiners", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "Tim Berners-Lee proposed the concept of WWW in which year?",
    optionA: "1985", optionB: "1989", optionC: "1993", optionD: "1991", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which exam is conducted for admission to IITs in India?",
    optionA: "GATE", optionB: "JEE Advanced", optionC: "BITSAT", optionD: "VITEEE", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "The OSI model in networking has how many layers?",
    optionA: "4", optionB: "5", optionC: "6", optionD: "7", correct: "D" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which Indian city is known as the 'Silicon Valley of India'?",
    optionA: "Mumbai", optionB: "Hyderabad", optionC: "Bengaluru", optionD: "Pune", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "hard",
    text: "Moore's Law states that transistor count on a chip doubles approximately every:",
    optionA: "6 months", optionB: "1 year", optionC: "2 years", optionD: "5 years", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "easy",
    text: "The full form of AI in technology is:",
    optionA: "Automated Interface", optionB: "Artificial Intelligence", optionC: "Analytic Integration", optionD: "Advanced Interconnect", correct: "B" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "Which country hosted the FIFA World Cup 2022?",
    optionA: "UAE", optionB: "Saudi Arabia", optionC: "Qatar", optionD: "Bahrain", correct: "C" },
  { category: "GENERAL_AWARENESS", difficulty: "medium",
    text: "The full form of 'GPS' is:",
    optionA: "General Positioning Service", optionB: "Global Positioning System", optionC: "Geographic Path Satellite", optionD: "Ground Placement System", correct: "B" },

  // ==================== BASIC ENGINEERING (40 unique) ====================
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "Ohm's Law states: V = ?",
    optionA: "I / R", optionB: "I x R", optionC: "R / I", optionD: "I + R", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "The SI unit of electrical resistance is:",
    optionA: "Volt", optionB: "Ampere", optionC: "Watt", optionD: "Ohm", correct: "D" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "Which material is the best conductor of electricity?",
    optionA: "Iron", optionB: "Copper", optionC: "Aluminium", optionD: "Steel", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "The unit of electric power is:",
    optionA: "Joule", optionB: "Volt", optionC: "Watt", optionD: "Ampere", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "In a series circuit, the total resistance is:",
    optionA: "Less than the smallest resistance", optionB: "Sum of all resistances", optionC: "Average of all resistances", optionD: "Product of all resistances", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "Which device converts AC to DC?",
    optionA: "Transformer", optionB: "Rectifier", optionC: "Inverter", optionD: "Amplifier", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "The full form of PCB in electronics is:",
    optionA: "Printed Circuit Board", optionB: "Power Control Block", optionC: "Processor Circuit Base", optionD: "Programmable Control Board", correct: "A" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "In data structures, LIFO stands for:",
    optionA: "Last In First Out", optionB: "Last In Final Output", optionC: "Least Input First Output", optionD: "Last Instance First Order", correct: "A" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "Which data structure uses FIFO (First In First Out) principle?",
    optionA: "Stack", optionB: "Tree", optionC: "Queue", optionD: "Graph", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "The language closest to machine language is:",
    optionA: "Python", optionB: "Assembly Language", optionC: "C++", optionD: "Java", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "What is the time complexity of Binary Search?",
    optionA: "O(n)", optionB: "O(n squared)", optionC: "O(log n)", optionD: "O(1)", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "Which logic gate gives output 1 only when both inputs are 1?",
    optionA: "OR", optionB: "NOT", optionC: "XOR", optionD: "AND", correct: "D" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "The 1's complement of the binary number 1010 is:",
    optionA: "0101", optionB: "1001", optionC: "0110", optionD: "1100", correct: "A" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "Kirchhoff's Current Law (KCL) states that the algebraic sum of currents at a node equals:",
    optionA: "Maximum current", optionB: "Minimum current", optionC: "Zero", optionD: "Total voltage", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "In object-oriented programming, hiding internal details is called:",
    optionA: "Inheritance", optionB: "Polymorphism", optionC: "Encapsulation", optionD: "Abstraction", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "Which of these is NOT an object-oriented programming language?",
    optionA: "Java", optionB: "C", optionC: "C++", optionD: "Python", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "In networking, IP stands for:",
    optionA: "Internet Processor", optionB: "Internal Protocol", optionC: "Internet Protocol", optionD: "Interconnect Path", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "The boiling point of water at standard atmospheric pressure is:",
    optionA: "90 degrees C", optionB: "95 degrees C", optionC: "100 degrees C", optionD: "105 degrees C", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "A semiconductor has conductivity:",
    optionA: "Very high like metals", optionB: "Zero like insulators", optionC: "Between conductors and insulators", optionD: "Negative", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "Which sorting algorithm has best average-case time complexity O(n log n)?",
    optionA: "Bubble Sort", optionB: "Insertion Sort", optionC: "Merge Sort", optionD: "Selection Sort", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "A 4-bit binary number can represent a maximum decimal value of:",
    optionA: "8", optionB: "15", optionC: "16", optionD: "32", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "A transformer has primary 100 turns and secondary 500 turns, input voltage 20V. Output voltage = ?",
    optionA: "4V", optionB: "100V", optionC: "200V", optionD: "500V", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "Which protocol is used for secure web communication (HTTPS)?",
    optionA: "FTP", optionB: "SSL/TLS", optionC: "SMTP", optionD: "UDP", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "In a relational database, a primary key must be:",
    optionA: "Nullable", optionB: "Duplicate", optionC: "Unique and Not Null", optionD: "Numeric only", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "The material used in making optical fibres is:",
    optionA: "Copper", optionB: "Glass/Silica", optionC: "Plastic only", optionD: "Aluminium", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "HTML stands for:",
    optionA: "HyperText Markup Language", optionB: "High Terminal Machine Language", optionC: "HyperText Machine Link", optionD: "Hosted Text Markup Language", correct: "A" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "Which type of memory is volatile?",
    optionA: "ROM", optionB: "Flash Memory", optionC: "RAM", optionD: "SSD", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "Pipelining in processors is used to:",
    optionA: "Reduce power consumption", optionB: "Increase clock speed physically", optionC: "Overlap multiple instruction phases for higher throughput", optionD: "Reduce memory usage", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "A diode allows current to flow in:",
    optionA: "Both directions", optionB: "Only one direction", optionC: "No direction", optionD: "Three directions", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "In C language, 'printf' is used for:",
    optionA: "Taking input", optionB: "Printing output", optionC: "Memory allocation", optionD: "File handling", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "Deadlock in an OS occurs when:",
    optionA: "CPU overheats", optionB: "Two or more processes wait indefinitely for resources held by each other", optionC: "Memory is full", optionD: "Network connection fails", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "In civil engineering, RCC stands for:",
    optionA: "Rigid Concrete Construction", optionB: "Reinforced Cement Concrete", optionC: "Random Composite Concrete", optionD: "Rapid Cure Concrete", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "The first law of thermodynamics states that:",
    optionA: "Entropy always increases", optionB: "Energy cannot be created or destroyed, only converted", optionC: "Temperature of an ideal gas is absolute", optionD: "Pressure and volume are inversely proportional", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "easy",
    text: "In mechanical engineering, stress is defined as:",
    optionA: "Force x Area", optionB: "Force / Area", optionC: "Area / Force", optionD: "Mass x Acceleration", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "SQL stands for:",
    optionA: "Simple Query Language", optionB: "Structured Query Language", optionC: "Sequential Query Logic", optionD: "System Query Language", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "In compiler design, lexical analysis is performed by:",
    optionA: "Parser", optionB: "Code Generator", optionC: "Scanner/Lexer", optionD: "Optimizer", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "The process of dividing a disk into sectors and tracks is called:",
    optionA: "Partitioning", optionB: "Formatting", optionC: "Fragmentation", optionD: "Clustering", correct: "B" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "NPN and PNP are types of:",
    optionA: "Diodes", optionB: "Capacitors", optionC: "Transistors", optionD: "Inductors", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "medium",
    text: "In digital electronics, XOR gate output is 1 when:",
    optionA: "Both inputs are 0", optionB: "Both inputs are 1", optionC: "Inputs are different", optionD: "Both inputs are equal", correct: "C" },
  { category: "BASIC_ENGINEERING", difficulty: "hard",
    text: "Virtual memory in an OS is:",
    optionA: "Extra physical RAM", optionB: "Memory on the GPU", optionC: "Disk space used as an extension of RAM", optionD: "Cache memory", correct: "C" },

  // ==================== MATHEMATICS (40 unique) ====================
  { category: "MATHEMATICS", difficulty: "easy",
    text: "What is the value of sin 90 degrees?",
    optionA: "0", optionB: "1", optionC: "root2/2", optionD: "root3/2", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "Area of a circle with radius 7 cm (pi = 22/7) = ?",
    optionA: "44 sq cm", optionB: "154 sq cm", optionC: "144 sq cm", optionD: "22 sq cm", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "The derivative of x^n with respect to x is:",
    optionA: "n x^n", optionB: "x^(n-1)", optionC: "n x^(n-1)", optionD: "n x", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "What is 2 raised to the power 8?",
    optionA: "128", optionB: "256", optionC: "512", optionD: "64", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "The sum of all angles of a triangle is:",
    optionA: "90 degrees", optionB: "180 degrees", optionC: "270 degrees", optionD: "360 degrees", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "The value of 0! (zero factorial) is:",
    optionA: "0", optionB: "Undefined", optionC: "1", optionD: "Infinity", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "What is the slope of the line y = 3x + 5?",
    optionA: "5", optionB: "3", optionC: "8", optionD: "15", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "The value of cos 0 degrees is:",
    optionA: "0", optionB: "1", optionC: "-1", optionD: "root2/2", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "A quadratic equation has discriminant D = b^2 - 4ac. If D > 0, roots are:",
    optionA: "Equal", optionB: "Imaginary", optionC: "Real and distinct", optionD: "Complex", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "log base 10 of 100 = ?",
    optionA: "1", optionB: "2", optionC: "10", optionD: "100", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The integral of x dx = ?",
    optionA: "x + C", optionB: "x^2 / 2 + C", optionC: "2x + C", optionD: "x^3 / 3 + C", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The number of ways to arrange 4 distinct books on a shelf = ?",
    optionA: "8", optionB: "16", optionC: "24", optionD: "32", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "If A = {1,2,3} and B = {2,3,4}, then A intersection B = ?",
    optionA: "{1,2,3,4}", optionB: "{2,3}", optionC: "{1,4}", optionD: "empty set", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The value of tan 45 degrees is:",
    optionA: "0", optionB: "root3", optionC: "1/root2", optionD: "1", correct: "D" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The volume of a sphere of radius r is:",
    optionA: "2 pi r^2", optionB: "pi r^3", optionC: "(4/3) pi r^3", optionD: "4 pi r^2", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "If f(x) = x^2 + 2x, then f'(x) (first derivative) = ?",
    optionA: "x + 2", optionB: "2x + 2", optionC: "2x", optionD: "x^2 + 2", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "Sum of an infinite geometric series a + ar + ar^2 + ... where |r| < 1 is:",
    optionA: "a/(1+r)", optionB: "a/(r-1)", optionC: "a/(1-r)", optionD: "ar/(1-r)", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The rank of a 2x2 identity matrix is:",
    optionA: "0", optionB: "1", optionC: "2", optionD: "4", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "Number of ways to choose a committee of 3 from 7 people (combination) = ?",
    optionA: "21", optionB: "35", optionC: "42", optionD: "28", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The line x = 5 is parallel to the:",
    optionA: "x-axis", optionB: "y-axis", optionC: "z-axis", optionD: "origin", correct: "B" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "The Laplace transform of e^(at) is:",
    optionA: "s/(s-a)", optionB: "1/(s+a)", optionC: "1/(s-a)", optionD: "a/(s+a)", correct: "C" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "For a 3x3 matrix, the maximum number of eigenvalues is:",
    optionA: "1", optionB: "2", optionC: "3", optionD: "9", correct: "C" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "The limit of (sin x)/x as x approaches 0 is:",
    optionA: "0", optionB: "infinity", optionC: "undefined", optionD: "1", correct: "D" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "The general solution of dy/dx = y is:",
    optionA: "y = x + C", optionB: "y = C e^x", optionC: "y = C ln(x)", optionD: "y = C x^2", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The distance between points (1,2) and (4,6) is:",
    optionA: "4", optionB: "5", optionC: "6", optionD: "7", correct: "B" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "Pythagoras theorem: In a right triangle with legs a, b and hypotenuse c: a^2 + b^2 = ?",
    optionA: "c", optionB: "c^2", optionC: "2c", optionD: "2c^2", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "What is i^2 where i is the imaginary unit (i = sqrt(-1))?",
    optionA: "1", optionB: "i", optionC: "-1", optionD: "-i", correct: "C" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "The Fourier series represents a periodic function as a sum of:",
    optionA: "Polynomials", optionB: "Exponentials", optionC: "Sines and cosines", optionD: "Logarithms", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "The product of a matrix A and identity matrix I equals:",
    optionA: "I", optionB: "Zero matrix", optionC: "A", optionD: "A^2", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The value of e^0 is:",
    optionA: "0", optionB: "e", optionC: "1", optionD: "infinity", correct: "C" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "If A and B are mutually exclusive events, P(A union B) = ?",
    optionA: "P(A) x P(B)", optionB: "P(A) + P(B) - P(A intersection B)", optionC: "P(A) + P(B)", optionD: "P(A) - P(B)", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The trace of a matrix is the sum of its:",
    optionA: "All elements", optionB: "Off-diagonal elements", optionC: "Diagonal elements", optionD: "Maximum elements in each row", correct: "C" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "sin^2(theta) + cos^2(theta) = ?",
    optionA: "0", optionB: "2", optionC: "sin 2theta", optionD: "1", correct: "D" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "The number of prime numbers between 1 and 20 is:",
    optionA: "6", optionB: "7", optionC: "8", optionD: "9", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "Area of a triangle with base 10 cm and height 6 cm = ?",
    optionA: "30 sq cm", optionB: "60 sq cm", optionC: "15 sq cm", optionD: "120 sq cm", correct: "A" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The derivative of sin(x) with respect to x is:",
    optionA: "-cos(x)", optionB: "cos(x)", optionC: "tan(x)", optionD: "-sin(x)", correct: "B" },
  { category: "MATHEMATICS", difficulty: "hard",
    text: "A second-order differential equation requires how many initial conditions for a unique solution?",
    optionA: "1", optionB: "2", optionC: "3", optionD: "4", correct: "B" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "Which of the following is NOT necessarily a property of a group?",
    optionA: "Closure", optionB: "Associativity", optionC: "Commutativity", optionD: "Identity element", correct: "C" },
  { category: "MATHEMATICS", difficulty: "easy",
    text: "What is 12^2 minus 5^2?",
    optionA: "119", optionB: "144", optionC: "121", optionD: "169", correct: "A" },
  { category: "MATHEMATICS", difficulty: "medium",
    text: "The roots of x^2 - 5x + 6 = 0 are:",
    optionA: "2 and 3", optionB: "1 and 6", optionC: "-2 and -3", optionD: "3 and 4", correct: "A" },
];

async function main() {
  console.log("=========================================");
  console.log("  MITChoice Engineering Admissions 2025");
  console.log("  Database Seed Script");
  console.log("  Made by: MITRASEN YADAV");
  console.log("  M.Tech CSE, NIT Hamirpur (NITH)");
  console.log("=========================================\n");

  // Admin user
  const adminPassword = await bcrypt.hash("admin123", 10);
  await prisma.user.upsert({
    where: { email: "admin@mitchoice.com" },
    update: {},
    create: {
      name: "Admin User",
      email: "admin@mitchoice.com",
      phone: "9999999999",
      password: adminPassword,
      role: "ADMIN",
    },
  });
  console.log("✅ Admin     → admin@mitchoice.com / admin123");

  // Demo student (named after the developer)
  const studentPassword = await bcrypt.hash("student123", 10);
  await prisma.user.upsert({
    where: { email: "demo@mitchoice.com" },
    update: {},
    create: {
      name: "Mitrasen Yadav",
      email: "demo@mitchoice.com",
      phone: "8888888888",
      password: studentPassword,
      role: "STUDENT",
    },
  });
  console.log("✅ Student   → demo@mitchoice.com / student123\n");

  // Wipe and re-seed questions
  await prisma.question.deleteMany();

  // Validate no duplicates
  const texts = allQuestions.map(q => q.text);
  const unique = new Set(texts);
  if (unique.size !== texts.length) {
    const dups = texts.filter((t, i) => texts.indexOf(t) !== i);
    console.warn("⚠️  Duplicate questions found:", dups);
  }

  await prisma.question.createMany({ data: allQuestions });

  // Summary
  const categories = ["ENGLISH", "NUMERICAL_APTITUDE", "GENERAL_AWARENESS", "BASIC_ENGINEERING", "MATHEMATICS"];
  console.log("📚 Question Bank:");
  for (const cat of categories) {
    const count = allQuestions.filter(q => q.category === cat).length;
    const easy = allQuestions.filter(q => q.category === cat && q.difficulty === "easy").length;
    const med  = allQuestions.filter(q => q.category === cat && q.difficulty === "medium").length;
    const hard = allQuestions.filter(q => q.category === cat && q.difficulty === "hard").length;
    console.log(`   ${cat.padEnd(24)} → ${count} Q  (easy:${easy} med:${med} hard:${hard})`);
  }
  console.log(`   ${"TOTAL".padEnd(24)} → ${allQuestions.length} questions`);
  console.log("\n📝 Quiz format: 25 questions per student");
  console.log("   5 from each category, randomly selected");
  console.log("\n🎉 Seed complete!\n");
}

main()
  .catch((e) => { console.error("Seed error:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
